version: '3'

services:
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: casabonita_soketi
    ports:
      - '6001:6001'
      - '9601:9601'
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: 'casa-bonita-app'
      SOKETI_DEFAULT_APP_KEY: 'casa-bonita-key'
      SOKETI_DEFAULT_APP_SECRET: 'casa-bonita-secret'
    restart: unless-stopped
